name: imtapp
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.5.0-191.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  lottie: ^3.1.2
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.0
  flutter_slidable: ^3.1.1
  easy_localization: ^3.0.7
  board_datetime_picker: ^2.0.0
  image_picker: ^1.1.2

  uuid:
    ^4.4.0

    #firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.2
  dio: ^5.5.0+1

flutter_native_splash:
  android: true
  ios: true
  web: false
  background_image: "assets/image/imtBackground.png"
  image: "assets/image/imt.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/imtLogo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/lottie/AnimationSignup.json
    - assets/lottie/AnimationLogin.json
    - assets/lang/
    - assets/image/
