// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtPDXe3LXO92QRGkMaJaRkxTnWR4xkEaA',
    appId: '1:1009352058137:web:9a6a9c0f21f9b777bc9188',
    messagingSenderId: '1009352058137',
    projectId: 'imtapp16',
    authDomain: 'imtapp16.firebaseapp.com',
    storageBucket: 'imtapp16.appspot.com',
    measurementId: 'G-QLRRGD4M4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRDEByDl4X5OjXUAI5cp1jAI40okjriho',
    appId: '1:1009352058137:android:379e748d2da84712bc9188',
    messagingSenderId: '1009352058137',
    projectId: 'imtapp16',
    storageBucket: 'imtapp16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0p9PQ63xJ3KEQz2UhpDgEKVy-SLuniiE',
    appId: '1:1009352058137:ios:0479d0684e638067bc9188',
    messagingSenderId: '1009352058137',
    projectId: 'imtapp16',
    storageBucket: 'imtapp16.appspot.com',
    iosBundleId: 'com.example.imtapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0p9PQ63xJ3KEQz2UhpDgEKVy-SLuniiE',
    appId: '1:1009352058137:ios:0479d0684e638067bc9188',
    messagingSenderId: '1009352058137',
    projectId: 'imtapp16',
    storageBucket: 'imtapp16.appspot.com',
    iosBundleId: 'com.example.imtapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtPDXe3LXO92QRGkMaJaRkxTnWR4xkEaA',
    appId: '1:1009352058137:web:2369ff8753821ac5bc9188',
    messagingSenderId: '1009352058137',
    projectId: 'imtapp16',
    authDomain: 'imtapp16.firebaseapp.com',
    storageBucket: 'imtapp16.appspot.com',
    measurementId: 'G-M40PLVE1GG',
  );
}
